version: '3'
services:
  db:
    container_name: postgresql
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=my-app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  web:
    container_name: web-app
    image: my-app
    environment:
      _JAVA_OPTIONS: ${_JAVA_OPTIONS:--Xms512M -Xmx1024M}
      _SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql/my-app
    ports:
      - 8082:8082
    depends_on:
      - db