server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my-app?cuurentSchema=public&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
        temp:
          user_jdbc_metadata_defaults: false
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: update